-- H2-compatible schema (dev profile)
-- For Oracle production DDL see scripts/oracle-schema.sql

CREATE TABLE IF NOT EXISTS batch_records (
    id            BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id   VARCHAR(255),
    name          VARCHAR(255)   NOT NULL,
    "value"       DECIMAL(20,4),
    category      VARCHAR(100),
    event_ts      TIMESTAMP,
    record_hash   VARCHAR(64)    NOT NULL,
    job_id        VARCHAR(100),
    partition_idx INTEGER,
    created_at    TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
    status        VARCHAR(20)    DEFAULT 'LOADED',
    CONSTRAINT uq_record_hash UNIQUE (record_hash)
);

CREATE INDEX IF NOT EXISTS idx_batch_records_job ON batch_records (job_id, partition_idx);

CREATE TABLE IF NOT EXISTS job_file_log (
    file_id          VARCHAR(255)  PRIMARY KEY,
    status           VARCHAR(20)   NOT NULL DEFAULT 'PROCESSING',
    job_execution_id BIGINT,
    started_at       TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    completed_at     TIMESTAMP,
    record_count     BIGINT,
    error_message    VARCHAR(2000)
);
