-- Production Oracle DDL
-- Run as DBA before first deployment

CREATE TABLE batch_records (
    id              NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id     VARCHAR2(255),
    name            VARCHAR2(255)   NOT NULL,
    value           NUMBER(20,4),
    category        VARCHAR2(100),
    event_ts        TIMESTAMP,
    record_hash     VARCHAR2(64)    NOT NULL,
    job_id          VARCHAR2(100),
    partition_idx   NUMBER(4),
    created_at      TIMESTAMP       DEFAULT SYSDATE NOT NULL,
    status          VARCHAR2(20)    DEFAULT 'LOADED' NOT NULL
) NOLOGGING TABLESPACE batch_data;

ALTER TABLE batch_records ADD CONSTRAINT uq_batch_record_hash UNIQUE (record_hash);
CREATE INDEX idx_batch_job ON batch_records (job_id, partition_idx) NOLOGGING;

-- CACHE 1000: critical for parallel insert performance
CREATE SEQUENCE batch_seq START WITH 1 INCREMENT BY 1 CACHE 1000 NOCYCLE;

CREATE TABLE job_file_log (
    file_id          VARCHAR2(255)  PRIMARY KEY,
    status           VARCHAR2(20)   NOT NULL DEFAULT 'PROCESSING',
    started_at       TIMESTAMP      DEFAULT SYSDATE NOT NULL,
    completed_at     TIMESTAMP,
    record_count     NUMBER,
    error_message    VARCHAR2(4000)
);

-- Run Spring Batch Oracle schema (from spring-batch-core jar):
-- schema-oracle.sql from spring-batch-core-5.x.x.jar!/org/springframework/batch/core/
